version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:15
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASS}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - easy-money-net
    volumes:
      - "postgres-data:/bitnami/postgresql"

  kafka:
    image: bitnami/kafka:3.5
    hostname: kafka
    container_name: kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    networks:
      - easy-money-net
    volumes:
      - "kafka-data:/bitnami/kafka"

  minio:
    image: bitnami/minio:2023
    hostname: minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${AWS_BUCKET}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - easy-money-net
    volumes:
      - "minio-data:/data"
      - "minio-data:/certs"

  backend-application:
    build:
      context: ./backend-application
      network: host
    image: backend-application:local
    hostname: backend-application
    container_name: backend-application
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DOWNLOADS_PATH: ${DOWNLOADS_PATH}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - easy-money-net
    volumes:
      - "backend-app-data:${DOWNLOADS_PATH}"
    depends_on:
      - postgres
      - kafka
      - minio

  spark-master:
    image: bitnami/spark:3.4
    hostname: spark-master
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
      SPARK_DAEMON_JAVA_OPTS: "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - easy-money-net
    volumes:
      - "spark-data:/opt/bitnami/spark/work"

  spark-worker:
    image: bitnami/spark:3.4
    hostname: spark-worker
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
      SPARK_DAEMON_JAVA_OPTS: "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8081:8081"
    networks:
      - easy-money-net
    volumes:
      - "spark-data:/opt/bitnami/spark/work"
    depends_on:
      - spark-master

  spark-builder:
    build:
      context: ./spark-qr-decoder
    hostname: spark-builder
    container_name: spark-builder
    volumes:
      - "spark-data:/opt/bitnami/spark/work"
    environment:
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: easy-money
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
      MASTER: spark://spark-master:7077
      PHOTO_INPUT_TOPIC: spark-photo
      PHOTO_OUTPUT_TOPIC: spark-photo-decoded
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - easy-money-net
    restart: no

networks:
  easy-money-net:
    driver: bridge

volumes:
  postgres-data:
  kafka-data:
  minio-data:
  backend-app-data:
  spark-data:
