apiVersion: v1
kind: Secret
metadata:
  namespace: easy-money
  name: postgres-secret
type: Opaque
data:
  username: "YWRtaW4K"
  postgres-password: "UEBzc3cwcmQK"
  replication-password: "UEBzc3cwcmQK"
  password: "UEBzc3cwcmQK"
  