server:
  port: ${SERVER_PORT:8080}

bot:
  telegram-token: ${BOT_TOKEN:#{'TOKEN'}}
  username: ${BOT_NAME:#{'@bot_name'}}

aws:
  access-key: ${AWS_ACCESS:#{'KEY'}}
  secret-key: ${AWS_SECRET:#{'KEY'}}
  region: ${AWS_REGION:#{'ru-central1'}}
  s3-bucket-name: ${AWS_BUCKET}
  multipart-min-part-size: 5242880 # 5MB
  endpoint: ${AWS_ENDPOINT:#{'https://storage.yandexcloud.net/'}}

logging:
  level:
    ru.yandex.practicum.de.kk91.easymoney.bot: INFO
    org:
      springframework:
        integration: INFO

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:#{'localhost:9092'}}
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/easy_money}
    username: ${DB_USER:admin}
    password: ${DB_PASS:P@ssw0rd}
