apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: easy-money
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: "5432"
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
  