apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
  namespace: easy-money
  labels:
    app: backend-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-application
  template:
    metadata:
      name: backend-application
      namespace: easy-money
      labels:
        app: backend-application
    spec:
      containers:
        - name: backend-application
          image: localhost:5000/backend-application:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-application-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/tmp"
              name: backend-data
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-application-pvc
      restartPolicy: Always
      