apiVersion: v1
kind: Service
metadata:
  name: backend-application-service
  namespace: easy-money
  labels:
    app: backend-application
spec:
  selector:
    app: backend-application
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
