apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-application-pv
  namespace: easy-money
  labels:
    app: backend-application
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/backend-application"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-application-pvc
  namespace: easy-money
  labels:
    app: backend-application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
