apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: easy-money
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      namespace: easy-money
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
            - containerPort: 9000
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          envFrom:
            - configMapRef:
                name: minio-config
          volumeMounts:
            - mountPath: /data
              name: minio-data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
      restartPolicy: Always
