apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-application.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "backend-application.labels" . | nindent 4 }}
{{- with .Values.config.environment}}
data:
  {{- toYaml . | nindent 2 }}
{{- end}}