apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: easy-money
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: "9092"
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: "9093"
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: "9094"
      protocol: TCP
      port: 9094
      targetPort: 9094
  type: NodePort
