apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: easy-money
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: "9090"
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: "9000"
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
