apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: easy-money
  name: storage-secret
data:
  AWS_ACCESS_KEY_ID: "NFdIcHZ4S3FLQW16dFpvaDVkZHIK"
  AWS_SECRET_ACCESS_KEY: "RWdISTI4V3AwWlRWWWYzOFNqTzVNNVkxQ1ljdTBXZDJmdWxpcVd3Swo="
  