apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: easy-money
  labels:
    app: kafka
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
