
## Bitnami Spark image version
## ref: https://hub.docker.com/r/bitnami/spark/tags/
## @param image.registry Spark image registry
## @param image.repository Spark image repository
## @param image.tag Spark image tag (immutable tags are recommended)
## @param image.digest Spark image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy Spark image pull policy
## @param image.pullSecrets Specify docker-registry secret names as an array
## @param image.debug Enable image debug mode
##
image:
  registry: docker.io
  repository: bitnami/spark
  tag: 3.4

## Spark master specific configuration
##
master:
  ## @param master.configOptions Use a string to set the config options for in the form "-Dx=y"
  ##
  configOptions:
    -Dspark.hadoop.fs.s3a.endpoint=https://storage.yandexcloud.net
    -Dspark.hadoop.fs.s3a.endpoint.region=ru-central1
    -Dspark.hadoop.fs.s3a.path.style.access=true
    --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  ## @param master.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for master nodes
  ##
  extraEnvVarsCM: "spark-config-env"
  ## @param master.extraEnvVarsSecret Name of existing Secret containing extra env vars for master nodes
  ##
  extraEnvVarsSecret: "storage-secret"

## Spark worker specific configuration
##
worker:
  ## @param worker.configOptions Set extra options to configure the worker in the form `-Dx=y`
  ##
  configOptions:
    -Dspark.hadoop.fs.s3a.endpoint=https://storage.yandexcloud.net
    -Dspark.hadoop.fs.s3a.endpoint.region=ru-central1
    -Dspark.hadoop.fs.s3a.path.style.access=true
    --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
  ## @param worker.extraEnvVarsCM Name of existing ConfigMap containing extra env vars for worker nodes
  ##
  extraEnvVarsCM: "spark-config-env"
  ## @param worker.extraEnvVarsSecret Name of existing Secret containing extra env vars for worker nodes
  ##
  extraEnvVarsSecret: "storage-secret"
  ## @param worker.replicaCount Number of spark workers (will be the minimum number when autoscaling is enabled)
  ##
  replicaCount: 1
